version: '3'
services:
  app:
    build: .  # Construye la imagen desde el Dockerfile en la carpeta actual
    container_name: partyapp  # nombre fijo para el contenedor
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app  # sincroniza la carpeta actual con el contenedor
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0  # para permitir acceso desde cualquier IP 
